### ISSUE TITLE
Add documentation to unsafe traits

### ISSUE THREAD

**Issue by mredlek** [sdroege/gobject-subclass#16]
There are some unsafe traits. With marking a trait as unsafe you say: "watch out, if the implementation of this trait doesn't fullfill all assumptions, then it can cause undefined behaviour". But which assumptions the implementor must respect isn't mentioned. 

Can you add documentation adding the assumptions the implementator must respect to not cause undefined behaviour?

**Comment by sdroege** [comment]
All this code is now merged into glib-rs now, I'll add docs there :) thanks

**Comment by sdroege** [comment]
The unsafe traits in glib's subclass module have this kind of documentation already, so it should all be fine. If not, just let me know what is missing :)
