### ISSUE TITLE
0.1.0 release

### ISSUE THREAD

**Issue by sdroege** [sdroege/gobject-subclass#4]
CC @vhdirk 

I'd like to do a first release of this to crates.io, so we have it available from there already when needed somewhere (like in your application or next time I do a gst-plugin-rs release).

Are there any things we should do before that, any changes you'd like to see before?

**Comment by vhdirk** [comment]
I think it's ready as is for a first release. I'm using the git version in my own application already, and so far it's working exactly as expected.
I suspect that for crates.io you would list the dependencies (glib, etc) from crates.io and not the git version?

**Comment by sdroege** [comment]
> I suspect that for crates.io you would list the dependencies (glib, etc) from crates.io and not the git version?

Yes, I don't think it's even possible to upload otherwise

**Comment by vhdirk** [comment]
It isn't. Not sure why I even asked :)

**Comment by sdroege** [comment]
I've also added https://github.com/sdroege/gobject-subclass/commit/3bfecd8f0037be2ae50d6f239aee621cc92a1a94 . Good that I noticed *before* releasing :)

**Comment by sdroege** [comment]
Will do release this evening unless something else comes up
